version: '1'
services:
    app:
        build: .
        ports:
            - 8888:8888
        environment:
            - NODE_ENV
            - APP_SERVER_HOST
            - APP_SERVER_PORT
            - STATIC_SERVER_MAX_AGE
        restart: on-failure
